# Generated by Django 5.1.1 on 2024-09-16 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testTaskApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='comments',
            name='text',
            field=models.TextField(),
        ),
    ]
